# Generated by Django 3.2.4 on 2021-07-05 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0044_auto_20210704_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='post_eva',
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 5), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 5), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 5), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 5), null=True),
        ),
        migrations.CreateModel(
            name='Skill_English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvc2', models.CharField(blank=True, max_length=200, null=True)),
                ('letter', models.CharField(blank=True, max_length=200, null=True)),
                ('cvc4', models.CharField(blank=True, max_length=200, null=True)),
                ('syllable', models.CharField(blank=True, max_length=200, null=True)),
                ('spelling', models.CharField(blank=True, max_length=200, null=True)),
                ('cvcd', models.CharField(blank=True, max_length=200, null=True)),
                ('vccv', models.CharField(blank=True, max_length=200, null=True)),
                ('iblends', models.CharField(blank=True, max_length=200, null=True)),
                ('fblends', models.CharField(blank=True, max_length=200, null=True)),
                ('review92', models.CharField(blank=True, max_length=200, null=True)),
                ('vcccv', models.CharField(blank=True, max_length=200, null=True)),
                ('ngnk', models.CharField(blank=True, max_length=200, null=True)),
                ('suffix', models.CharField(blank=True, max_length=200, null=True)),
                ('magic', models.CharField(blank=True, max_length=200, null=True)),
                ('magic_e', models.CharField(blank=True, max_length=200, null=True)),
                ('cvce_test', models.CharField(blank=True, max_length=200, null=True)),
                ('magic2e', models.CharField(blank=True, max_length=200, null=True)),
                ('smagice', models.CharField(blank=True, max_length=200, null=True)),
                ('vcv', models.CharField(blank=True, max_length=200, null=True)),
                ('ph', models.CharField(blank=True, max_length=200, null=True)),
                ('ck', models.CharField(blank=True, max_length=200, null=True)),
                ('vowel', models.CharField(blank=True, max_length=200, null=True)),
                ('kkck', models.CharField(blank=True, max_length=200, null=True)),
                ('erir', models.CharField(blank=True, max_length=200, null=True)),
                ('owou', models.CharField(blank=True, max_length=200, null=True)),
                ('igh', models.CharField(blank=True, max_length=200, null=True)),
                ('ble', models.CharField(blank=True, max_length=200, null=True)),
                ('le', models.CharField(blank=True, max_length=200, null=True)),
                ('yvy', models.CharField(blank=True, max_length=200, null=True)),
                ('ild', models.CharField(blank=True, max_length=200, null=True)),
                ('aror', models.CharField(blank=True, max_length=200, null=True)),
                ('oo', models.CharField(blank=True, max_length=200, null=True)),
                ('y_vowel', models.CharField(blank=True, max_length=200, null=True)),
                ('soft_c', models.CharField(blank=True, max_length=200, null=True)),
                ('soft_g', models.CharField(blank=True, max_length=200, null=True)),
                ('gedge', models.CharField(blank=True, max_length=200, null=True)),
                ('gc', models.CharField(blank=True, max_length=200, null=True)),
                ('auaw', models.CharField(blank=True, max_length=200, null=True)),
                ('tch', models.CharField(blank=True, max_length=200, null=True)),
                ('ing', models.CharField(blank=True, max_length=200, null=True)),
                ('vcv_spelling', models.CharField(blank=True, max_length=200, null=True)),
                ('three_s', models.CharField(blank=True, max_length=200, null=True)),
                ('schwa', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluation_regular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDA_app.evaluation_regular')),
            ],
        ),
    ]
