# Generated by Django 3.2.4 on 2021-07-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0045_auto_20210705_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arabic_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Arabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=200, null=True)),
                ('two', models.CharField(blank=True, max_length=200, null=True)),
                ('three', models.CharField(blank=True, max_length=200, null=True)),
                ('four', models.CharField(blank=True, max_length=200, null=True)),
                ('five', models.CharField(blank=True, max_length=200, null=True)),
                ('six', models.CharField(blank=True, max_length=200, null=True)),
                ('seven', models.CharField(blank=True, max_length=200, null=True)),
                ('eight', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluation_regular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDA_app.evaluation_regular')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDA_app.arabic_letter')),
            ],
        ),
    ]
