# Generated by Django 3.2.4 on 2021-07-07 05:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0046_arabic_letter_skill_arabic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_psy',
            name='cognitive_date',
        ),
        migrations.RemoveField(
            model_name='assessment_psy',
            name='cognitive_result',
        ),
        migrations.RemoveField(
            model_name='assessment_psy',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='assessment_psy',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 7), null=True),
        ),
        migrations.CreateModel(
            name='Cognitive_assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=300)),
                ('cognitive_date', models.DateField()),
                ('cognitive_result', models.TextField()),
                ('recommendations', models.TextField()),
                ('notice', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive2', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment_psy',
            name='cognitive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.cognitive_assessment'),
        ),
    ]
