# Generated by Django 3.2.4 on 2021-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0047_auto_20210707_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='subject',
            field=models.CharField(default='English', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
