# Generated by Django 3.2.4 on 2021-07-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0048_auto_20210707_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='pre_eva',
        ),
        migrations.AddField(
            model_name='pre_evaluation',
            name='skill',
            field=models.ManyToManyField(to='KDA_app.Skill'),
        ),
    ]
