# Generated by Django 3.2.4 on 2021-07-08 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0049_auto_20210707_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Arabic_Pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=200, null=True)),
                ('two', models.CharField(blank=True, max_length=200, null=True)),
                ('three', models.CharField(blank=True, max_length=200, null=True)),
                ('four', models.CharField(blank=True, max_length=200, null=True)),
                ('five', models.CharField(blank=True, max_length=200, null=True)),
                ('six', models.CharField(blank=True, max_length=200, null=True)),
                ('seven', models.CharField(blank=True, max_length=200, null=True)),
                ('eight', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_English_Pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=200)),
                ('two', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pre_evaluation',
            name='skill',
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 8), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 8), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 8), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 8), null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='skill_english_pre',
            name='pre_eva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_pre', to='KDA_app.pre_evaluation'),
        ),
        migrations.AddField(
            model_name='skill_arabic_pre',
            name='pre_eva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_pre_a', to='KDA_app.pre_evaluation'),
        ),
    ]
