# Generated by Django 3.2.4 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0050_auto_20210708_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='status',
            field=models.CharField(default='Open', max_length=200),
            preserve_default=False,
        ),
    ]
