# Generated by Django 3.2.4 on 2021-07-08 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0051_intervention_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 7, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=200),
        ),
    ]
