# Generated by Django 3.2.4 on 2021-07-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0052_auto_20210708_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention_Cancelled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KDA_app.intervention')),
            ],
        ),
    ]
