# Generated by Django 3.2.4 on 2021-07-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0053_intervention_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention_cancelled',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled1', to='KDA_app.intervention'),
        ),
    ]
