# Generated by Django 3.2.4 on 2021-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0055_alter_intervention_cancelled_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='s_language',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
