# Generated by Django 3.2.4 on 2021-07-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0056_auto_20210708_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re_Scheduled_Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled', to='KDA_app.intervention')),
            ],
        ),
    ]
