# Generated by Django 3.2.4 on 2021-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0060_auto_20210714_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_intervention',
            name='status',
            field=models.CharField(default='Attended', max_length=200),
        ),
    ]
