# Generated by Django 3.2.4 on 2021-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0062_auto_20210717_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_psy',
            name='sub_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
