# Generated by Django 3.2.4 on 2021-08-03 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0065_auto_20210728_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 3), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 3), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 3), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 3), null=True),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='spoc_f_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='spoc_l_name',
            field=models.CharField(max_length=300),
        ),
    ]
