# Generated by Django 3.2.4 on 2021-08-04 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0067_auto_20210804_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='psychologist',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
