# Generated by Django 3.2.4 on 2021-08-04 19:06

import KDA_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0068_alter_test_psychologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=KDA_app.models.Person.get_upload_path_id),
        ),
    ]
