# Generated by Django 3.2.4 on 2021-08-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0072_auto_20210816_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mobile_number',
        ),
    ]
