# Generated by Django 3.2.4 on 2021-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0073_remove_person_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
