# Generated by Django 3.2.4 on 2021-08-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0080_auto_20210826_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_intervention',
            name='intervention',
        ),
        migrations.AlterField(
            model_name='assessment_psy',
            name='cognitive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.cognitive_assessment'),
        ),
    ]
