# Generated by Django 3.2.4 on 2021-08-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0081_auto_20210826_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_intervention',
            name='intervention',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='all_intv', to='KDA_app.session'),
            preserve_default=False,
        ),
    ]
