# Generated by Django 3.2.4 on 2021-08-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0082_all_intervention_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_psy',
            name='child',
        ),
        migrations.RemoveField(
            model_name='assessment_psy',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='cognitive_assessment',
            name='child',
        ),
        migrations.RemoveField(
            model_name='cognitive_assessment',
            name='psychologist',
        ),
    ]
