# Generated by Django 3.2.4 on 2021-08-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0084_auto_20210827_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_intervention',
            old_name='intervention',
            new_name='session',
        ),
    ]
