# Generated by Django 3.2.4 on 2021-08-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0085_rename_intervention_all_intervention_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation_regular',
            name='student',
        ),
        migrations.RemoveField(
            model_name='evaluation_regular',
            name='teacher',
        ),
    ]
