# Generated by Django 3.2.4 on 2021-08-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0088_auto_20210830_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_arabic',
            name='skill_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_english',
            name='skill_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
