# Generated by Django 3.2.4 on 2021-08-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0089_auto_20210830_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_arabic',
            name='evaluation_regular',
        ),
        migrations.RemoveField(
            model_name='skill_english',
            name='evaluation_regular',
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='a_intervention',
            field=models.ManyToManyField(to='KDA_app.All_Intervention'),
        ),
        migrations.AddField(
            model_name='skill_english',
            name='a_intervention',
            field=models.ManyToManyField(to='KDA_app.All_Intervention'),
        ),
        migrations.AlterField(
            model_name='session',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='KDA_app.intervention'),
        ),
    ]
