# Generated by Django 3.2.4 on 2021-08-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0090_auto_20210830_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_arabic',
            name='grade',
            field=models.CharField(blank=True, choices=[('acceptable', 'مقبول'), ('good', 'جيد'), ('vgood', 'جيد جدا'), ('excellent', 'ممتاز')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_english',
            name='grade',
            field=models.CharField(blank=True, choices=[('mastery', 'Mastery'), ('n_mastery', 'Not Mastered')], max_length=200, null=True),
        ),
    ]
