# Generated by Django 3.2.4 on 2021-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0092_auto_20210830_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_english',
            name='grade',
        ),
        migrations.AddField(
            model_name='skill_english',
            name='grade',
            field=models.CharField(blank=True, choices=[('mastery', 'Mastery'), ('n_mastery', 'Not Mastered')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Grade_English',
        ),
    ]
