# Generated by Django 3.2.4 on 2021-08-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0093_auto_20210830_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_intervention',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill_arabic',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='skill_arabic',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='skill_english',
            name='a_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.all_intervention'),
        ),
        migrations.RemoveField(
            model_name='skill_arabic',
            name='a_intervention',
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='a_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.all_intervention'),
        ),
        migrations.RemoveField(
            model_name='skill_arabic',
            name='letter',
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.arabic_letter'),
        ),
    ]
