# Generated by Django 3.2.4 on 2021-08-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0094_auto_20210830_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_arabic',
            name='a_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='a_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='b_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='c_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='c_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='d_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='d_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='d_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='d_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='e_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='eight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='f_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='five',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='g_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='g_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='h_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='h_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='i_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='seven',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='six',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill_arabic',
            name='two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill_arabic',
            name='a_intervention',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.all_intervention'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill_arabic',
            name='letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.arabic_letter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill_english',
            name='a_intervention',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.all_intervention'),
            preserve_default=False,
        ),
    ]
