# Generated by Django 3.2.4 on 2021-09-06 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0096_auto_20210831_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Not_Active', 'Not Active')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 6), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 6), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 6), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 6), null=True),
        ),
    ]
