# Generated by Django 3.2.4 on 2021-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0097_auto_20210906_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pending_s_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
