# Generated by Django 3.2.4 on 2021-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0098_person_pending_s_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pending_e_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
