# Generated by Django 3.2.4 on 2021-09-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0099_person_pending_e_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pending_e_date',
        ),
    ]
