# Generated by Django 3.2.4 on 2021-09-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0100_remove_person_pending_e_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pending_s_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AddField(
            model_name='intervention',
            name='pending_s_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Not_Active', 'Not Active')], max_length=200, null=True),
        ),
    ]
