# Generated by Django 3.2.4 on 2021-09-07 11:15

import KDA_app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0102_session_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_case_data',
            name='date_last_assessment',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_1',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_2',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='child_case_data',
            name='enroll_date_3',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 7), null=True),
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworks', models.FileField(blank=True, null=True, upload_to=KDA_app.models.Homeworks.get_upload_path_homework)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='KDA_app.intervention')),
            ],
        ),
    ]
