# Generated by Django 3.2.4 on 2021-09-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0109_auto_20210922_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('parent_test_name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
                ('sub_score', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits1', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
